// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtendedShortcuts
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExtendedShortcuts.124780e7-c2c8-4e26-b574-9f0d62ff4ed9";
        public const string Name = "ExtendedShortcuts";
        public const string Description = @"ExtendedShortcuts is a VisualStudio 2022 extension intnded to provide shortcuts to various tasks in the development workflow. Currently supports Selecting and Building a favorite project via hotkeyExtendedShortcuts is a VisualStudio 2022 extension intnded to provide shortcuts to various tasks in the development workflow.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Tanner Van De Walle";
        public const string Tags = "";
    }
}
