// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtendedShortcuts
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExtendedShortcuts.124780e7-c2c8-4e26-b574-9f0d62ff4ed9";
        public const string Name = "ExtendedShortcuts";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tanner Van De Walle";
        public const string Tags = "";
    }
}
