// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtendedShortcuts
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ExtendedShortcutsString = "a0c9e1da-9573-4732-934b-5e24e1660625";
        public static Guid ExtendedShortcuts = new Guid(ExtendedShortcutsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int BuildFavoriteProject = 0x0100;
        public const int SetFavoriteProject = 0x0101;
    }
}